title: Reboot and shine!
email: weratt@gmail.com
description: >
  Ordinary software engineering blog about boring stuff.

url: "https://werat.github.io"
baseurl: ""

# TODO(werat): Migrate to shorter format.
permalink: /:year/:month/:day/:title

twitter_username: werat
github_username:  werat

disqus:
  shortname: werat-github-io
google_analytics: UA-91441325-1

theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
