title: Reboot and shine!
email: weratt@gmail.com
description: >
  Ordinary software engineering blog about boring stuff.

url: "https://werat.github.io"
baseurl: ""
permalink: /:year/:month/:day/:title

twitter_username: werat
github_username:  werat

disqus:
  shortname: werat-github-io
google_analytics: UA-91441325-1

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-remote-theme

remote_theme: jekyll/minima@3cdd14dff1216f561c68329e0b7420c2dc9b796a
