baseURL = "https://werat.dev/"
title = "Reboot and Shine"
theme = "hugo-coder"

disqusShortname = "werat-github-io"

[permalinks]
  posts = "/blog/:slug/"

[params]
  favicon_32 = "img/logo-avatar-32.png"
  favicon_16 = "img/logo-avatar-16.png"
  touchicon = "img/logo-avatar.png"

  author = "Andy Hippo"
  keywords = "blog,developer,personal"
  avatarURL = "img/logo-avatar.png"
  since = 2017
  colorScheme = "light"
  hideColorSchemeToggle = true
  customCSS = ["css/custom.css"]

# [params.googleTagManager]
#  id = "UA-91441325-1"

[params.goatCounter]
  code = "werat-dev"

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  style = "friendly"

[[params.social]]
  name = "Twitter"
  icon = "fa fa-2x fa-twitter"
  weight = 1
  url = "https://twitter.com/werat/"

[[params.social]]
  name = "Github"
  icon = "fa fa-2x fa-github"
  weight = 2
  url = "https://github.com/werat/"

[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-2x fa-linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/werat/"

[[params.social]]
  name = "Email"
  icon = "fa fa-2x fa-envelope-o"
  weight = 4
  url = "mailto:weratt@gmail.com"

[[params.social]]
  name = "RSS"
  icon = "fa fa-2x fa-rss"
  weight = 5
  url = "index.xml"
  rel = "alternate"
  type = "application/rss+xml"

[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"

[[menu.main]]
  name = "Talks"
  weight = 2
  url = "talks/"
