baseURL = "https://werat.dev/"
title = "werat.dev"

disqusShortname = "werat-github-io"

[permalinks]
  posts = "/blog/:slug/"

[params]
  favicon_32 = "img/logo-avatar-32.png"
  favicon_16 = "img/logo-avatar-16.png"

  author = "Andy Hippo"
  license = "MIT"
  license_url = "https://github.com/werat/werat.github.io/blob/main/LICENSE"
  keywords = "blog,developer,personal"
  avatarURL = "img/logo-avatar.jpg"
  since = 2017
  colorScheme = "light"
  hideColorSchemeToggle = true
  customCSS = ["css/custom.css"]

[params.goatCounter]
  code = "werat-dev"

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  style = "friendly"

[[params.social]]
  name = "Twitter"
  icon = "twitter"
  weight = 1
  url = "https://twitter.com/werat/"

[[params.social]]
  name = "Github"
  icon = "github"
  weight = 2
  url = "https://github.com/werat/"

[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/werat/"

[[params.social]]
  name = "Email"
  icon = "mail"
  weight = 4
  url = "mailto:weratt@gmail.com"

[[params.social]]
  name = "RSS"
  icon = "rss"
  weight = 5
  url = "index.xml"
  rel = "alternate"
  type = "application/rss+xml"

[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"

[[menu.main]]
  name = "Talks"
  weight = 2
  url = "talks/"
