baseURL = "https://werat.dev/"
title = "werat.dev"
disableKinds = ["taxonomy", "term"]

disqusShortname = "werat-github-io"

[permalinks]
  posts = "/blog/:slug/"

[params]
  author = "Andy Hippo"
  email = "weratt@gmail.com"
  twitter = "werat"
  license = "MIT"
  license_url = "https://github.com/werat/werat.github.io/blob/main/LICENSE"
  keywords = ["blog", "developer", "personal"]
  since = 2017

[params.goatCounter]
  code = "werat-dev"

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  style = "xcode"

[[params.social]]
  name = "Twitter"
  icon = "twitter"
  weight = 1
  url = "https://twitter.com/werat/"

[[params.social]]
  name = "Github"
  icon = "github"
  weight = 2
  url = "https://github.com/werat/"

[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/werat/"

[[params.social]]
  name = "Email"
  icon = "mail"
  weight = 4
  url = "mailto:weratt@gmail.com"

[[params.social]]
  name = "RSS"
  icon = "rss"
  weight = 5
  url = "index.xml"
  rel = "alternate"
  type = "application/rss+xml"

[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"

[[menu.main]]
  name = "Blog"
  weight = 2
  url  = "posts/"

[[menu.main]]
  name = "Talks"
  weight = 3
  url = "talks/"
